//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        public int MaGG { get; set; }
        public int MaSP { get; set; }
        public decimal PhanTramGiam { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
