//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoHang
    {
        public int MaKho { get; set; }
        public string TenKho { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MaSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
