//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.DanhGias = new HashSet<DanhGia>();
            this.KhoHangs = new HashSet<KhoHang>();
            this.GiamGias = new HashSet<GiamGia>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public decimal Gia { get; set; }
        public string Loai { get; set; }
        public string ChatLieu { get; set; }
        public string MauSac { get; set; }
        public string KichThuoc { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MaNCC { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual ICollection<KhoHang> KhoHangs { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual ICollection<GiamGia> GiamGias { get; set; }
    }
}
