//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuoiKy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CuoiKy.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evol Store - Share Your Color.
        /// </summary>
        public static string Footer_About_Title {
            get {
                return ResourceManager.GetString("Footer.About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ: TDM, Bình Dương.
        /// </summary>
        public static string Footer_Address {
            get {
                return ResourceManager.GetString("Footer.Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2023 evolstore | Powered by evolstore.
        /// </summary>
        public static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer.Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Footer_Email_Label {
            get {
                return ResourceManager.GetString("Footer.Email.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sđt.
        /// </summary>
        public static string Footer_Hotline_Label {
            get {
                return ResourceManager.GetString("Footer.Hotline.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotline.
        /// </summary>
        public static string Footer_Hotline_Title {
            get {
                return ResourceManager.GetString("Footer.Hotline.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký: Ngày 12/06/2021.
        /// </summary>
        public static string Footer_Registered {
            get {
                return ResourceManager.GetString("Footer.Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIỎ HÀNG.
        /// </summary>
        public static string Layout_Cart_Title {
            get {
                return ResourceManager.GetString("Layout.Cart.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evol Store.
        /// </summary>
        public static string Layout_Header_Brand {
            get {
                return ResourceManager.GetString("Layout.Header.Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIỚI THIỆU.
        /// </summary>
        public static string Layout_Nav_About {
            get {
                return ResourceManager.GetString("Layout.Nav.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIÊN HỆ.
        /// </summary>
        public static string Layout_Nav_Contact {
            get {
                return ResourceManager.GetString("Layout.Nav.Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỜI TRANG.
        /// </summary>
        public static string Layout_Nav_Fashion {
            get {
                return ResourceManager.GetString("Layout.Nav.Fashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANG CHỦ.
        /// </summary>
        public static string Layout_Nav_Home {
            get {
                return ResourceManager.GetString("Layout.Nav.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CỬA HÀNG.
        /// </summary>
        public static string Layout_Nav_Shop {
            get {
                return ResourceManager.GetString("Layout.Nav.Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÀI KHOẢN CỦA TÔI.
        /// </summary>
        public static string Layout_User_Account {
            get {
                return ResourceManager.GetString("Layout.User.Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG NHẬP.
        /// </summary>
        public static string Layout_User_Login {
            get {
                return ResourceManager.GetString("Layout.User.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG XUẤT.
        /// </summary>
        public static string Layout_User_Logout {
            get {
                return ResourceManager.GetString("Layout.User.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐƠN HÀNG CỦA TÔI.
        /// </summary>
        public static string Layout_User_Orders {
            get {
                return ResourceManager.GetString("Layout.User.Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG KÝ.
        /// </summary>
        public static string Layout_User_Register {
            get {
                return ResourceManager.GetString("Layout.User.Register", resourceCulture);
            }
        }
    }
}
